name: PWA Deploy

on: [push]

defaults:
  run:
    working-directory: ./angular
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14
      - run: npm install yarn -g
      - name: Install dependencies
        run: yarn install
      - name: 🙌 Build
        run: yarn build:prod
      - name: 📂 Sync files
        uses: SamKirkland/FTP-Deploy-Action@4.1.0
        with:
          server: server01.codext.de
          username: ${{ secrets.ftp_user }}
          password: ${{ secrets.ftp_password }}
          local-dir: ./www/
          server-dir: ./
